spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/computerstore?useUnicode=true&characterEncoding=utf-8&useSSL=false"
    username: "root"
    password: "youyang"
    driver-class-name: com.mysql.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

# 配置mybatis规则、使用MyBatisPlus则此项配置无效
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:  # 指定mybatis全局配置文件中的相关配置项
    # 开启驼峰
    map-underscore-to-camel-case: true